# Generated by Django 4.2.7 on 2025-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestratambor',
            name='fecha_de_extraccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
