# Generated by Django 4.2.7 on 2025-07-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_muestratambor_fecha_de_extraccion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pool',
            name='idx_pool_fechas',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='fecha_extraccion',
        ),
    ]
