# Generated by Django 4.2.7 on 2025-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_remove_pool_idx_pool_fechas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestratambor',
            name='estado_analisis_palinologico',
            field=models.BooleanField(default=False, help_text='True si el tambor está asignado a un grupo de análisis, False si está disponible'),
        ),
    ]
